version: '3.8'

services:
  # Servicio principal de an치lisis
  analisis-videojuegos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videogame_analysis
    volumes:
      # Montar carpeta de datos (donde est치 vgsales.csv)
      - ./data:/app/data
      # Montar carpeta de salida (para gr치ficas y reportes)
      - ./output:/app/output
      # Montar c칩digo para desarrollo en vivo
      - ./analisis_videojuegos.py:/app/analisis_videojuegos.py
    environment:
      - DATASET_PATH=/app/data/vgsales.csv
      - OUTPUT_PATH=/app/output
    restart: unless-stopped